### PR TITLE
Ygl for master

### PR DESCRIPTION
**Pull request by Yanok35**
Few updates for master branch.

### CODE REVIEW

**Comment by gdoffe** [comment]
Please Yannick, could you do some separated PR according to thematics ?
The controller commit has nothing related to simulation ones.

Moreover we said to the last meeting that simulation have to be reworked as FreeCAD is a bottleneck.
A start has been intitated here: https://github.com/cogip/mcu-firmware/commit/f046c40b38386a1581bb8232cb63cbba9c45619c

IMHO maintaining the actual (old ?) simulation code is a waste of time.

However the controller correction seems good to me. Thank you.

**Comment by Yanok35** [comment]
> Please Yannick, could you do some separated PR according to thematics ?
> The controller commit has nothing related to simulation ones.

Ok, updated.

> 
> Moreover we said to the last meeting that simulation have to be reworked as FreeCAD is a bottleneck.
> A start has been intitated here: [f046c40](https://github.com/cogip/mcu-firmware/commit/f046c40b38386a1581bb8232cb63cbba9c45619c)
> 
> IMHO maintaining the actual (old ?) simulation code is a waste of time.

The code updated is related to feedback control loop monitoring and display graphs to observe how Kp, Ki and Kd tuning changes the feedback loop response. This is different topic than whole robot displacement and actions.

> 
> However the controller correction seems good to me. Thank you.

**Comment by gdoffe** [comment]
> The code updated is related to feedback control loop monitoring and display graphs to observe how Kp, Ki and Kd tuning changes the feedback loop response. This is different topic than whole robot displacement and actions.

I'm still thinking it should be better to spend the effort on a new real simulation tool, coupling telemetry and robot simulation and actions.
The first thing to do should be the listing of awaited features of this new tool.
Maybe we could talk about that at the next cogip meeting, draws and schematics would help.

**Comment by gdoffe** [comment]
LGTM.

@Kheprys @ecourtois : one more review please.

**Pull request merged**
