### PR TITLE
Uncrustify update

### PR DESCRIPTION
**Pull request by Kheprys**
Update check-codingrules script to only check if file are compliant with config or not.

It then display diff between uncrustified generated files and original to display what is missing.

Also add a new makefile target 'make check-codingrules' and add this step to github workflow

### CODE REVIEW

**Review by gdoffe — COMMENTED** [review]
tools: update uncrustify coding rules

Update config to stuck C pointer * on type instead of var name.

**Review by gdoffe — COMMENTED** [review]
tools: update tools/check-codingrules.sh

Only check if source file are compliant and display diff

* add new make command 'make check-codingrules'
* update git workflow to check codingrules

**Review by gdoffe — COMMENTED** [review]
According to team concertation, we should drop this commit to keep pointer star stucked to the type.

**Review by ecourtois — APPROVED** [review]
LGMT

**Review by ecourtois — CHANGES_REQUESTED** [review]
Can you document in README.md how to run this check manually?

**Comment by Kheprys** [comment]
> Can you document in README.md how to run this check manually?

Done !

**Review by ecourtois — APPROVED** [review]
LGTM

**Pull request merged**
