### PR TITLE
VL53L0X emulation

### PR DESCRIPTION
**Pull request by gdoffe**
Add some optims and comments before adding support of vl53l0x sensors stubbed emulation.

### CODE REVIEW

**Comment by gdoffe** [comment]
> * "_automatically initialized to 0_": are you sure?

yes because you cannot initialize partially a struct. All non initialized members are initialized to zero:
https://en.cppreference.com/w/c/language/struct_initialization

Do you agree with that ?

**Comment by gdoffe** [comment]
> Function**s**

done

**Comment by gdoffe** [comment]
> peripheral**s**?

done

**Comment by gdoffe** [comment]
> boards:cogip2019-cortex => boards: cogip2019-cortex (missing space)

done

**Review by ecourtois — APPROVED** [review]
LGMT

**Pull request merged**
